/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
    "./app/Livewire/**/*.php",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#ffb4a8",
        "surface-container-high": "#eae7e7",
        "secondary": "#b6171e",
        "on-tertiary-container": "#ff9f9b",
        "outline-variant": "#e4beb8",
        "outline": "#8f706b",
        "secondary-fixed": "#ffdad6",
        "surface-dim": "#dcd9d9",
        "surface": "#fcf9f8",
        "surface-bright": "#fcf9f8",
        "error-container": "#ffdad6",
        "surface-variant": "#e5e2e1",
        "on-tertiary-fixed-variant": "#91081a",
        "on-tertiary-fixed": "#410005",
        "tertiary": "#6d000f",
        "tertiary-fixed-dim": "#ffb3af",
        "secondary-container": "#da3433",
        "on-secondary-fixed": "#410003",
        "surface-container-low": "#f6f3f2",
        "primary-fixed": "#ffdad4",
        "primary-fixed-dim": "#ffb4a8",
        "primary-container": "#990000",
        "on-surface-variant": "#5b403c",
        "on-surface": "#1b1c1c",
        "secondary-fixed-dim": "#ffb3ac",
        "surface-container-highest": "#e5e2e1",
        "primary": "#6e0000",
        "on-error-container": "#93000a",
        "background": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#930000",
        "surface-tint": "#b82014",
        "on-background": "#1b1c1c",
        "inverse-on-surface": "#f3f0ef",
        "tertiary-container": "#950d1c",
        "error": "#ba1a1a",
        "inverse-surface": "#303030",
        "surface-container": "#f0eded",
        "on-primary-fixed": "#410000",
        "tertiary-fixed": "#ffdad7",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#fffbff",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#930010",
        "on-primary-container": "#ffa092"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "40px",
        "gutter": "16px",
        "sm": "8px",
        "xl": "32px",
        "lg": "24px",
        "md": "16px",
        "xs": "4px",
        "unit": "4px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "code-sm": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"]
      },
      fontSize: {
        "code-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "title-lg": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
